### ISSUE TITLE
Buggy state

### ISSUE THREAD

**Issue by Fritz-CO-KG** [toqix/InvasionMLG-Rush#16]
After helping creating a map, the map was finished
I typed /startgame and it wouldn't let me join the queue (maybe typed /build and sth else idk.)
Then i had to leave and it wouldn't work.
I typed /startgame and it worked fine

**Comment by toqix** [comment]
A remake of the state system is planned anyways to reduce these bugs, because as it is right now it's a bad coded system, which leads to many bugs.

**Comment by toqix** [comment]
these bugs shouldn't occur anymore

**Comment by Fritz-CO-KG** [comment]
brav

**Comment by toqix** [comment]
jaja sehr brav
